---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{jiravolumename}}
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium-retain
    resources:
    requests:
      storage: {{storagesize}}